=== GuillermoMediero/Reto-1g-Sendy-Guille-Unai/xml/Clasificacion.dtd
<!ELEMENT Clasificacion (Posicion+)>
<!ELEMENT Posicion (NOMBRE,PARTIDOS_JUGADOS,VICTORIAS,DERROTAS,PUNTOS)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT PARTIDOS_JUGADOS (#PCDATA)>
<!ELEMENT VICTORIAS (#PCDATA)>
<!ELEMENT DERROTAS (#PCDATA)>
<!ELEMENT PUNTOS (#PCDATA)>

=== GuillermoMediero/Reto-1g-Sendy-Guille-Unai/xml/Clasificacion.xml
<?xml version="1.0" encoding="Cp1252"?>
<!DOCTYPE jornadas SYSTEM "Clasificacion.dtd">
<Clasificacion xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Clasificacion.xsd">
 <Posicion>
  <NOMBRE>ROMPEMUROS</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>LOS PITUFOS</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>LOS INCREIBLES</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>LEG BROKERS</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>hola</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>CHAIR MONSTERS</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>BLACK BIRDS</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
 <Posicion>
  <NOMBRE>Adios</NOMBRE>
  <PARTIDOS_JUGADOS>14</PARTIDOS_JUGADOS>
  <VICTORIAS>0</VICTORIAS>
  <DERROTAS>0</DERROTAS>
  <PUNTOS>0</PUNTOS>
 </Posicion>
</Clasificacion>
